[build]
  base = "Ace Web Designers Website/Ace Web Designers Website"
  publish = "Ace Web Designers Website/Ace Web Designers Website/dist"
  command = "npm ci && npm run build"
  functions = "Ace Web Designers Website/Ace Web Designers Website/netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200