-- 0009_niche_playbooks.sql
-- Niche knowledge base + per-appointment sales brief.
--
-- `niche_playbooks` is the researched, reusable knowledge for one trade (how its
-- customers buy, what the website must do, market pricing ranges with sources,
-- pitch angles) — written by the `generate-brief` Edge Function's research stage
-- (Claude + web search) and refreshed when stale, NOT hand-seeded here: content
-- must carry real sources and an `as_of` date, which only live research provides.
-- A generic in-code FALLBACK_PLAYBOOK (functions/_shared/nichePlaybooks.ts) keeps
-- brief/site generation working when this table is empty or unreadable.

create table if not exists public.niche_playbooks (
  id                      text primary key,           -- slug, e.g. 'plumber'
  display_name            text not null,
  trades                  text[] not null default '{}', -- match keywords (same matcher as design_systems)
  how_customers_buy       text not null default '',
  must_have_site_features text not null default '',
  credibility_levers      text not null default '',
  pitch_angles            text not null default '',   -- offer framing grounded in named sales frameworks
  upsell_ladder           text not null default '',
  common_objections       text not null default '',
  pricing                 jsonb not null default '[]'::jsonb, -- [{item, low, high, source, as_of}]
  sources                 jsonb not null default '[]'::jsonb, -- [{title, url}]
  active                  boolean not null default true,
  sort                    int not null default 0,
  researched_at           timestamptz,                -- staleness marker; re-research when old
  updated_at              timestamptz not null default now()
);

alter table public.niche_playbooks enable row level security;
-- Edge Functions use the service_role key (bypasses RLS). Authenticated admins may read.
drop policy if exists "niche_playbooks read" on public.niche_playbooks;
create policy "niche_playbooks read" on public.niche_playbooks for select to authenticated using (true);

-- Per-appointment pre-meeting sales brief (markdown), generated by `generate-brief`.
alter table public.appointments
  add column if not exists sales_brief        text,
  add column if not exists brief_status       text check (brief_status in ('queued', 'generating', 'ready', 'failed')),
  add column if not exists brief_error        text,
  add column if not exists brief_generated_at timestamptz;
